name: 'Autotag'

on: 
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**/*.yml'
      - '.gitignore'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json
          token: ${{ secrets.GITHUB_TOKEN }}
